### ISSUE TITLE
Custom environments

### ISSUE THREAD

**Issue by ghost** [queckezz/pwdx#1]
What about adding the option to create custom environments and not only limitting yourself to `ssh` and `web`? I know in your `readme` you write to feel free to open an issue to ask about adding more but I'm asking myself if it's really worth it having only hard-coded environments.

Maybe I'm missing something or I'm not seeing something... What is your intention behind this?

**Comment by queckezz** [comment]
Ah I guess it's to keep it consistent and later add some validation logic so you don't mistype the environment (like SSH instead of ssh etc). You are kinda right though, it theoretically doesn't have to be a set of fixed environments.

**Comment by ghost** [comment]
Oh yes, that makes sense of course. I'm working on a .NET implementation of your project and was thinking wether I should implement it exactly the same way. I'll let you know when I published my repo! Thanks for your answer.
